services:
  postgres:
    image: postgres:17-alpine
    ports: 
      - 1111:5432
    environment:
      POSTGRES_DB: cor_proj
      POSTGRES_USER: cor_proj
      POSTGRES_PASSWORD: cor_proj
    volumes:
      - "db:/var/lib/postgresql/data"

  redis:
    image: redis:8.0-M03-alpine
    ports:
      - 6379:6379
    volumes:
      - redis:/data


volumes:
  db:
  redis: