services:
  postgres:
    image: postgres:17-alpine
    ports: 
      - 1111:5432
    environment:
      POSTGRES_DB: cor_proj
      POSTGRES_USER: cor_proj
      POSTGRES_PASSWORD: cor_proj
    volumes:
      - "db:/var/lib/postgresql/data"

volumes:
  db: